#!/bin/bash

cd $HOME
source .profile
DefaultPlumbing="$HOME/.config/plumber/plumbing"
if [ -f $DefaultPlumbing ]; then
	$PLAN9/bin/plumber -p $DefaultPlumbing
else
	$PLAN9/bin/plumber
fi
$PLAN9/bin/fontsrv &
#font='/mnt/font/Roboto Regular/12a/font'
lfont='/mnt/font/SourceCodePro-Medium/14a/font'
tabstop=4 \
  TERM=dumb \
  BROWSER='google-chrome' \
  SHELL=/bin/bash \
  acmeshell=/bin/bash \
  acmeshellflags="-ic" \
  EDITOR=E \
  PATH=$PATH \
  PAGER=nobs \
   /usr/local/plan9/bin/acme -a -b -f $lfont
